spring:
  application:
    name: TaskManager
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DB:task_manager_database}
    username: ${POSTGRES_USER:application}
    password: ${POSTGRES_PASSWORD:su}
    driver-class-name: org.postgresql.Driver
    jpa:
      database: postgresql
      generate-ddl: false
    main:
      allow-bean-definition-overriding: true
  kafka:
    bootstrap-servers: localhost:29092

logging:
  level:
    ROOT: INFO
  file:
    path: ./logs/

t1:
  kafka:
    bootstrap:
      server: localhost:29092
    consumer:
      group-id: t1-task
      max.poll.records: 10
    producer:
      enable: true
    topic:
      tasks_update: t1-task-updates
    listener:
      poll_timeout: 1000